### ISSUE TITLE
Incorrect Class reference to Model/Service/ShopperHandlerService.php in /Model/Methods/AlternativePaymentMethod.php

### ISSUE THREAD

**Issue by lakshmana** [checkout/checkout-magento2-plugin#508]
The class `CheckoutCom\Magento2\Model\Service\ShopperHandlerService` is referenced with lowercases classname as `CheckoutCom\Magento2\Model\Service\shopperHandlerService` in `CheckoutCom\Magento2\Model\Methods\AlternativePaymentMethod` https://github.com/checkout/checkout-magento2-plugin/blob/9ae2ea6477c6a98b4f7aeb1d3d758978b7e54e3e/Model/Methods/AlternativePaymentMethod.php#L48 
Because of this the autoloader throw a fatal error similar to this 
```
Fatal error: Uncaught ReflectionException: Class CheckoutCom\Magento2\Model\Service\shopperHandlerService does not exist in /vendor/magento/framework/Code/Reader/ClassReader.php:36 Stack trace: 
#0 /vendor/magento/framework/Code/Reader/ClassReader.php(36): ReflectionParameter->getClass() 
#1 /vendor/magento/framework/ObjectManager/Definition/Runtime.php(54): Magento\Framework\Code\Reader\ClassReader->getConstructor() 
#2 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\Framework\ObjectManager\Definition\Runtime->getParameters() 
#3 /vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() 
#4 /services/checkout-test.php(16): Magento\Framework\ObjectManager\ObjectManager->get() 
#5 {main} Next ReflectionException: Class CheckoutCom\Magento2\Model\Service\shopperHandlerService does not exist in /var/ww in /vendor/magento/framework/Code/Reader/ClassReader.php on line 43
```
A fix is as simple as updating the FQCN as `CheckoutCom\Magento2\Model\Service\ShopperHandlerService`

**Comment by Dnd-Gimix** [comment]
Hello @lakshmana 

We have provided a preventive bug fix for this issue in the latest 3.1.1 version of the extension.
Can you please have a look at it and inform us of the resolution of your issue?

Many thanks.
Regards,
